// this code is convert from https://github.com/PaddlePaddle/PaddleX
// PaddleX's source code IS Licensed under the Apache License Version 2.0
/*
 *    Copyright 2026 the original author or authors.
 *
 *    Licensed under the Apache License, Version 2.0 (the "License");
 *    you may not use this file except in compliance with the License.
 *    You may obtain a copy of the License at
 *
 *       http://www.apache.org/licenses/LICENSE-2.0
 *
 *    Unless required by applicable law or agreed to in writing, software
 *    distributed under the License is distributed on an "AS IS" BASIS,
 *    WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 *    See the License for the specific language governing permissions and
 *    limitations under the License.
 */
package io.github.flux.formula.paddle;

import ai.djl.huggingface.tokenizers.HuggingFaceTokenizer;
import ai.djl.ndarray.NDArray;
import io.github.flux.util.ArrayUtil;

import java.nio.file.Path;
import java.util.ArrayList;
import java.util.Arrays;
import java.util.List;
import java.util.Map;
import java.util.regex.Matcher;
import java.util.regex.Pattern;

/**
 * <p>Class for decoding tokenized inputs using UniMERNet tokenizer.</p>
 * <p>generated by Claude Sonnet 4</p>
 */
public class UniMERNetDecode {

    // Special token attributes
    private static final List<String> SPECIAL_TOKENS_ATTRIBUTES = Arrays.asList(
            "bos_token", "eos_token", "unk_token", "sep_token",
            "pad_token", "cls_token", "mask_token", "additional_special_tokens"
    );

    // Instance variables
    private final List<String> modelInputNames;
    private final int maxSeqLen;
    private final int padTokenId;
    private final int bosTokenId;
    private final int eosTokenId;
    private final String paddingSide;
    private final String padToken;
    private final int padTokenTypeId;
    private final Integer padToMultipleOf;

    private String unkToken = "<unk>";
    private String bosToken = "<s>";
    private String eosToken = "</s>";
    private String padTokenStr = "<pad>";
    private String sepToken = null;
    private String clsToken = null;
    private String maskToken = null;
    private List<String> additionalSpecialTokens = new ArrayList<>();

    private HuggingFaceTokenizer tokenizer;

    /**
     * Initializes the UniMERNetDecode class.
     *
     * @param tokenizerPath
     */
    public UniMERNetDecode(Path tokenizerPath, Map<String, String> options) {
        this.modelInputNames = Arrays.asList("input_ids", "token_type_ids", "attention_mask");
        this.maxSeqLen = 2048;
        this.padTokenId = 1;
        this.bosTokenId = 0;
        this.eosTokenId = 2;
        this.paddingSide = "right";
        this.padToken = "<pad>";
        this.padTokenTypeId = 0;
        this.padToMultipleOf = null;

        try {
            this.tokenizer = HuggingFaceTokenizer.newInstance(tokenizerPath, options);
        } catch (Exception e) {
            throw new RuntimeException("Failed to initialize tokenizer", e);
        }
    }

    /**
     * Converts token IDs to token strings.
     *
     * @param ids Token ID(s) to convert
     * @param skipSpecialTokens Whether to skip special tokens during conversion
     * @return Converted token string(s)
     */
    public Object convertIdsToTokens(Object ids, boolean skipSpecialTokens) {
        if (ids instanceof Integer) {
            return tokenizer.decode(new long[]{(Integer) ids}, skipSpecialTokens);
        } else if (ids instanceof List) {
            @SuppressWarnings("unchecked")
            List<Integer> idList = (List<Integer>) ids;
            List<String> tokens = new ArrayList<>();

            for (Integer id : idList) {
                if (skipSpecialTokens && isSpecialToken(id)) {
                    continue;
                }
                String token = tokenizer.decode(new long[]{id}, false);
                tokens.add(token);
            }
            return tokens;
        }
        throw new IllegalArgumentException("ids must be Integer or List<Integer>");
    }

    /**
     * Checks if a token ID represents a special token.
     */
    private boolean isSpecialToken(int tokenId) {
        return tokenId == bosTokenId || tokenId == eosTokenId || tokenId == padTokenId;
    }

    /**
     * Detokenizes a list of token IDs back into strings.
     *
     * @param tokens List of token ID lists
     * @return List of detokenized strings
     */
    public List<List<String>> detokenize(List<List<Integer>> tokens) {
        List<List<String>> result = new ArrayList<>();

        for (List<Integer> tokenList : tokens) {
            @SuppressWarnings("unchecked")
            List<String> toks = (List<String>) convertIdsToTokens(tokenList, false);

            // Process tokens in reverse order for removal
            for (int i = toks.size() - 1; i >= 0; i--) {
                String token = toks.get(i);
                if (token == null) {
                    toks.set(i, "");
                } else {
                    token = token.replace("臓", " ").trim();
                    if (token.equals(bosToken) || token.equals(eosToken) || token.equals(padTokenStr)) {
                        toks.remove(i);
                    } else {
                        toks.set(i, token);
                    }
                }
            }
            result.add(toks);
        }
        return result;
    }

    /**
     * Converts a list of token IDs to strings.
     *
     * @param tokenIds NDArray containing token lists
     * @return List of converted strings
     */
    public List<String> token2str(NDArray tokenIds) {
        List<String> generatedText = new ArrayList<>();

        // Convert NDArray to long arrays for processing
        long[][] tokenArrays = ArrayUtil.convertToLongArray(tokenIds);

        for (long[] tokId : tokenArrays) {
            // Find end token (ID 2)
            int endIdx = -1;
            for (int i = 0; i < tokId.length; i++) {
                if (tokId[i] == 2) {
                    endIdx = i;
                    break;
                }
            }

            // Truncate at end token if found
            long[] processedTokId;
            if (endIdx >= 0) {
                processedTokId = Arrays.copyOf(tokId, endIdx + 1);
            } else {
                processedTokId = tokId;
            }

            // Decode tokens
            String decoded = tokenizer.decode(processedTokId, true);
            generatedText.add(postProcess(decoded));
        }

        return generatedText;
    }

    /**
     * Normalizes a string by removing unnecessary spaces.
     *
     * @param s String to normalize
     * @return Normalized string
     */
    public String normalize(String s) {
        String textReg = "(\\\\(operatorname|mathrm|text|mathbf)\\s?\\*? \\{.*?\\})";
        String letter = "[a-zA-Z]";
        String noletter = "[\\W_^\\d]";

        Pattern textPattern = Pattern.compile(textReg);
        Matcher textMatcher = textPattern.matcher(s);
        List<String> names = new ArrayList<>();

        while (textMatcher.find()) {
            String match = textMatcher.group(0);
            Pattern pattern = Pattern.compile("(\\\\[a-zA-Z]+)\\s(?=\\w)|\\\\[a-zA-Z]+\\s(?=\\})");
            Matcher matcher = pattern.matcher(match);

            while (matcher.find()) {
                String m = matcher.group(1) != null ? matcher.group(1) : matcher.group(0);
                if (!Arrays.asList("\\operatorname", "\\mathrm", "\\text", "\\mathbf").contains(m)
                        && !m.trim().isEmpty()) {
                    s = s.replace(m, m + "XXXXXXX");
                    s = s.replace(" ", "");
                    names.add(s);
                }
            }
        }

        if (!names.isEmpty()) {
            Pattern replacePattern = Pattern.compile(textReg);
            Matcher replaceMatcher = replacePattern.matcher(s);
            StringBuffer sb = new StringBuffer();
            int nameIndex = 0;

            while (replaceMatcher.find() && nameIndex < names.size()) {
                replaceMatcher.appendReplacement(sb, names.get(nameIndex++));
            }
            replaceMatcher.appendTail(sb);
            s = sb.toString();
        }

        String news = s;
        while (true) {
            s = news;
            news = s.replaceAll("(?!\\\\ )(" + noletter + ")\\s+?(" + noletter + ")", "$1$2");
            news = news.replaceAll("(?!\\\\ )(" + noletter + ")\\s+?(" + letter + ")", "$1$2");
            news = news.replaceAll("(" + letter + ")\\s+?(" + noletter + ")", "$1$2");
            if (news.equals(s)) {
                break;
            }
        }

        return s.replace("XXXXXXX", " ");
    }

    /**
     * Removes Chinese text wrapping from formulas.
     */
    public String removeChineseTextWrapping(String formula) {
        Pattern pattern = Pattern.compile("\\\\text\\s*\\{\\s*([^}]*?[\\u4e00-\\u9fff]+[^}]*?)\\s*\\}");
        Matcher matcher = pattern.matcher(formula);

        StringBuffer sb = new StringBuffer();
        while (matcher.find()) {
            matcher.appendReplacement(sb, matcher.group(1));
        }
        matcher.appendTail(sb);

        return sb.toString().replace("\"", "");
    }

    /**
     * Post-processes a string by fixing text and normalizing it.
     *
     * @param text String to post-process
     * @return Post-processed string
     */
    public String postProcess(String text) {
        // Note: ftfy functionality would need to be implemented separately or use a Java equivalent
        text = removeChineseTextWrapping(text);
        text = normalize(text);
        return text;
    }

    /**
     * Processes predictions returning the decoded text.
     *
     * @param preds Model predictions as NDArray
     * @return Decoded text
     */
    public List<String> call(NDArray preds) {
        return token2str(preds);
    }

    // Getters for configuration values
    public List<String> getModelInputNames() { return modelInputNames; }
    public int getMaxSeqLen() { return maxSeqLen; }
    public int getPadTokenId() { return padTokenId; }
    public int getBosTokenId() { return bosTokenId; }
    public int getEosTokenId() { return eosTokenId; }
    public String getPaddingSide() { return paddingSide; }
    public String getPadToken() { return padToken; }
    public int getPadTokenTypeId() { return padTokenTypeId; }
    public Integer getPadToMultipleOf() { return padToMultipleOf; }
}