"""Compare tokens generated by transformers vs ONNX inference."""

transformers_tokens = [13628, 10, 69, 1953, 422, 49, 32, 50, 125, 386,
    97, 44, 272, 44, 571, 1659, 2547, 12105, 32, 48,
    41, 377, 1659, 3861, 92, 7420, 11811, 36387, 9102, 108,
    322, 16978, 1659, 11972, 422, 49, 9102, 50, 125, 1659,
    10435, 32, 50, 1659, 27772, 38, 44, 7333, 92, 11972,
    25817, 4886, 9102, 52, 125, 1659, 25631, 32, 50, 1659,
    27772, 1659, 10435, 32, 50, 1659, 27772, 561, 1659, 10435,
    32, 50, 1659, 27772, 1170, 1659, 7104, 828, 1067, 1659,
    51686, 1659, 27772, 1067, 16630, 25817, 25631, 94, 422, 50,
    125, 32, 50, 1659, 27772, 1093, 32, 50, 125, 3664,
    38, 44, 7333, 45, 1659, 10435, 32, 50, 1659, 27772,
    38, 44, 7333, 45, 1659, 11972, 422, 49, 9102, 50,
    125, 1659, 10435, 32, 50, 1659, 27772, 1659, 3861, 91,
    32, 49, 1170, 32, 50, 32, 52, 386, 49, 32,
    57, 1170, 32, 53, 1659, 10435, 32, 52, 1659, 27772,
    41, 16630, 422, 45, 32, 49, 125, 1659, 2547, 47855,
    44, 7333, 45, 386, 53, 32, 51, 1659, 10435, 32,
    50, 1659, 27772, 1170, 32, 55, 1659, 10435, 32, 54,
    1659, 27772, 41, 386, 51, 32, 57, 1170, 32, 50,
    32, 49, 1659, 10435, 32, 52, 1659, 27772, 41, 16630,
    422, 45, 32, 49, 125, 38, 22623, 486, 36387, 6542,
    2547, 334, 13628, 59253]

onnx_tokens = [13628, 10, 69, 1953, 422, 49, 32, 50, 125, 386, 97, 44, 272, 44, 571, 1659, 2547, 12105, 32, 48, 41, 377, 1659, 3861, 92, 7420, 11811, 36387, 9102, 108, 322, 16978, 1659, 11972, 422, 49, 9102, 50, 125, 1659, 10435, 32, 50, 1659, 27772, 7333, 92, 11972, 25817, 4886, 9102, 52, 125, 1659, 25631, 32, 50, 1659, 27772, 1659, 10435, 32, 50, 1659, 27772, 561, 1659, 10435, 32, 50, 1659, 27772, 1170, 1659, 7104, 828, 1067, 1659, 51686, 1659, 27772, 1067, 16630, 25817, 25631, 94, 422, 50, 125, 32, 50, 1659, 27772, 1093, 32, 50, 125, 3664, 7333, 45, 1659, 10435, 32, 50, 1659, 27772, 7333, 45, 1659, 10435, 32, 50, 1659, 27772, 7333, 45, 1659, 11972, 422, 49, 9102, 50, 125, 1659, 10435, 32, 50, 1659, 27772, 1659, 3861, 91, 32, 49, 1170, 32, 50, 32, 52, 386, 49, 32, 57, 1170, 32, 53, 1659, 10435, 32, 52, 1659, 27772, 41, 16630, 422, 45, 32, 49, 125, 1659, 2547, 93, 7333, 45, 1659, 11972, 422, 49, 9102, 50, 125, 1659, 10435, 32, 50, 1659, 27772, 1659, 3861, 91, 32, 49, 1170, 32, 50, 32, 52, 386, 49, 32, 57, 1170, 32, 53, 1659, 10435, 32, 52, 1659, 27772, 41, 16630, 422, 45, 32, 49, 125, 1659, 2547, 93, 7333, 45, 386, 53, 32, 51, 1659, 10435, 32, 50, 1659, 27772, 1170, 32, 55, 1659, 10435, 32, 54, 1659, 27772, 41, 386, 51, 32, 57, 1170, 32, 50, 32, 49, 1659, 10435, 32, 52, 1659, 27772, 41, 16630, 422, 45, 32, 49, 6542, 486, 36387, 6542, 2547, 334, 13628, 59253]

from transformers import AutoProcessor
MODEL_PATH = r"D:\models\GLM-OCR"
processor = AutoProcessor.from_pretrained(MODEL_PATH, trust_remote_code=True)
tokenizer = processor.tokenizer

print(f"Transformers tokens: {len(transformers_tokens)}")
print(f"ONNX tokens:         {len(onnx_tokens)}")
print()

# Find first divergence
for i in range(min(len(transformers_tokens), len(onnx_tokens))):
    if transformers_tokens[i] != onnx_tokens[i]:
        # Show context around divergence
        start = max(0, i - 5)
        end = min(len(transformers_tokens), len(onnx_tokens), i + 10)
        
        print(f"FIRST DIVERGENCE at token index {i}")
        print(f"  Transformers token: {transformers_tokens[i]} -> '{tokenizer.decode([transformers_tokens[i]])}'")  
        print(f"  ONNX token:         {onnx_tokens[i]} -> '{tokenizer.decode([onnx_tokens[i]])}'")
        print()
        
        # Context before
        print(f"  Context (indices {start}-{i-1}):")
        for j in range(start, i):
            print(f"    [{j}] {transformers_tokens[j]} -> '{tokenizer.decode([transformers_tokens[j]])}'")
        print()
        
        # Show all differences  
        print("ALL DIFFERENCES:")
        break

diffs = []
for i in range(min(len(transformers_tokens), len(onnx_tokens))):
    if transformers_tokens[i] != onnx_tokens[i]:
        t_text = tokenizer.decode([transformers_tokens[i]])
        o_text = tokenizer.decode([onnx_tokens[i]])
        diffs.append((i, transformers_tokens[i], t_text, onnx_tokens[i], o_text))

print(f"\nTotal differences: {len(diffs)} out of {min(len(transformers_tokens), len(onnx_tokens))} tokens")
print(f"{'Idx':>4} | {'Trans ID':>8} {'Trans Text':>20} | {'ONNX ID':>8} {'ONNX Text':>20}")
print("-" * 75)
for idx, t_id, t_text, o_id, o_text in diffs:
    print(f"{idx:>4} | {t_id:>8} {repr(t_text):>20} | {o_id:>8} {repr(o_text):>20}")

print()
print("=== Transformers decoded ===")
print(tokenizer.decode(transformers_tokens, skip_special_tokens=True))
print()
print("=== ONNX decoded ===")
print(tokenizer.decode(onnx_tokens, skip_special_tokens=True))
